version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sap
    container_name: sap-app
    #restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sap

  db:
    image: mariadb
    container_name: sap-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - sap

  nginx:
    image: nginx:alpine
    container_name: sap-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sap

networks:
  sap:
    driver: bridge